FROM apache/airflow:2.8.0
USER root
RUN apt-get update && apt-get install -y gcc python3-dev && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir duckdb==0.10.0 confluent-kafka==2.3.0 dbt-duckdb==1.7.0